# Generated by Django 4.1.3 on 2022-11-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='labels',
            field=models.ManyToManyField(related_name='notes_labels', to='notes.labels'),
        ),
    ]
